config/routes.rb
Rails.application.routes.draw do

  

 

  root "static_pages#home"

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/gettingstarted',    to: 'static_pages#GettingStarted'
  get  '/faq',   to: 'static_pages#faq'
  get   '/join', to: 'users#new'
  post '/join',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: {maximum: 35}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
  format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
    	flash.now[:danger] = 'Invalid email/password boi!'
    render 'new'
  end
end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end


  def help
  end

  def GettingStarted
  end

  def faq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
def show
	@user = User.find(params[:id])
end

  def new
  	@user = User.new
  end


  def create
    @user = User.new(user_params)   # Not the final implementation!
    if @user.save
    	log_in @user
    	flash[:success] = "Welcome to the club mateu!"
      redirect_to @user
    else
      render 'new'
  end
end


      




      private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
      

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
		
		def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def logged_in?
  	!current_user.nil?
  end
  






  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '#' %></li>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | @RooM8p</title>
		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

	<body>
  		<nav>
  			<div class="container">
    			<div class="twelve columns">
          			<ul class="nav-load">
            			<li class="site-name"><%= link_to "RooM8", root_path, id: "logo"%></li>
            			<li class="hidden-mobile"><%= link_to "Contact",   contact_path %></li>
            			<li class="hidden-mobile"><%= link_to "About",   about_path %></li>
            			<li class="hidden-mobile"><%= link_to "Getting Started",   gettingstarted_path %></li>
            			<li class="hidden-mobile"><%= link_to "FAQ",   faq_path %></li>
            			<li><%= link_to "Log in", login_path %></li>
                  <% if logged_in? %>
                  <li><%= link_to "Users", '#' %></li>
                  <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
        		</div>
      		</div>
    	</nav>

<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
<%= yield %>
	<!-- <%= render 'layouts/footer' %> -->
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/GettingStarted.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | @RooM8</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/_header.html.erb
<nav>
  <div class="container">
    <div class="twelve columns">
        <%= link_to "sample app", '#', id: "logo" %>
          <ul class="nav-load">
            <li class="site-name"><%= link_to "Home",   '#' %></li>
            <li class="hidden-mobile"><%= link_to "Help",   '#' %></li>
            <li class="hidden-mobile"><%= link_to "Log in", '#' %></li>
          </ul>
        </div>
      </div>
    </nav>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | @RooM8</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | @RooM8</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>
  <body>
  	<section id ="inner">
    	<div class ="container">
      		<div class ="twelve columns front">
        		<div id ="Word-Column">
          		<h1>We're always available!</h1>
          		<h2>Have a question, or need some help?

</h2>
<p>Check out the help sections on the left. If you still can’t find an answer, send us feedback.

</p>
        	</div>
        </div>
    </div>
</section>
  </body>
</html>

app/views/static_pages/faq.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | @RooM8</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | @RooM8</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | @ RooM8</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <section id ="Main">
    <div class ="container">
      <div class ="twelve columns front">
        <div id ="Word-Wrapper">
          <h1 class="fadeInDown animated" data-wow-duration="2
          s" style="visibility: visible; animation-duration: 1.75s; animation-name: fadeInDown;">Hey kid, how's that shit feel!<div class="heading_border"></div></h1>
          <div class="fadeInUp animated" data-wow-duration="2s" style="visibility: visible; animation-duration: 1.75s; animation-name: fadeInUp;">
        <a href="/join" class="button button-primary">Join Us!</a>
        <a href="/gettingstarted" class="button button-secondary">Learn More</a>
      </div>
        </div>


</div>
</div>
</section>
	 </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: join_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>